/**
 * Whatsapp-bot
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InteractiveReplyData } from './interactiveReplyData';
import { TextData } from './textData';

export interface MessagesData { 
    from?: string;
    id?: string;
    timestamp?: string;
    text?: TextData;
    interactive?: InteractiveReplyData;
    type?: string;
    readonly isReply?: boolean;
}