/**
 * Whatsapp-bot
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { MoneyMovement } from '../model/moneyMovement';
import { MoneyMovementResult } from '../model/moneyMovementResult';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';



@Injectable({providedIn: 'root'})
export class MoneyMovementService {

    protected basePath = '/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional() configuration: Configuration) {
        if (BASE_PATH) {
            this.basePath = BASE_PATH;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = BASE_PATH || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param moneyMovementId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public moneyMovementDeleteDelete(xUserKey: string, moneyMovementId: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public moneyMovementDeleteDelete(xUserKey: string, moneyMovementId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public moneyMovementDeleteDelete(xUserKey: string, moneyMovementId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public moneyMovementDeleteDelete(xUserKey: string, moneyMovementId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (moneyMovementId !== undefined && moneyMovementId !== null) {
            queryParameters = queryParameters.set('moneyMovementId', <any>moneyMovementId);
        }

        let headers = this.defaultHeaders;
        if (xUserKey !== undefined && xUserKey !== null) {
            headers = headers.set('X-User-Key', String(xUserKey));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('delete',`${this.basePath}/MoneyMovement/Delete`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param xUserKey 
     * @param beginDate 
     * @param endDate 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public moneyMovementGetGet(xUserKey?: string, beginDate?: Date, endDate?: Date, observe?: 'body', reportProgress?: boolean): Observable<MoneyMovementResult>;
    public moneyMovementGetGet(xUserKey?: string, beginDate?: Date, endDate?: Date, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<MoneyMovementResult>>;
    public moneyMovementGetGet(xUserKey?: string, beginDate?: Date, endDate?: Date, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<MoneyMovementResult>>;
    public moneyMovementGetGet(xUserKey?: string, beginDate?: Date, endDate?: Date, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {




        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (beginDate !== undefined && beginDate !== null) {
            queryParameters = queryParameters.set('beginDate', <any>beginDate.toISOString());
        }
        if (endDate !== undefined && endDate !== null) {
            queryParameters = queryParameters.set('endDate', <any>endDate.toISOString());
        }

        let headers = this.defaultHeaders;
        if (xUserKey !== undefined && xUserKey !== null) {
            headers = headers.set('X-User-Key', String(xUserKey));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<MoneyMovementResult>('get',`${this.basePath}/MoneyMovement/Get`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param xUserKey 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public moneyMovementUpdatePut(body?: MoneyMovement, xUserKey?: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public moneyMovementUpdatePut(body?: MoneyMovement, xUserKey?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public moneyMovementUpdatePut(body?: MoneyMovement, xUserKey?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public moneyMovementUpdatePut(body?: MoneyMovement, xUserKey?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {



        let headers = this.defaultHeaders;
        if (xUserKey !== undefined && xUserKey !== null) {
            headers = headers.set('X-User-Key', String(xUserKey));
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('put',`${this.basePath}/MoneyMovement/Update`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
